# Generated by Django 3.2.14 on 2022-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discription_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delevered', 'Delevered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TV', 'TV'), ('W', 'Watch'), ('FG', 'Fridge'), ('EP', 'Earphone'), ('PR', 'Printer'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=12),
        ),
    ]
